name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-n3ds:
    name: Build (N3DS)
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y git make 3ds-dev 3ds-tools 3ds-libctru

      - uses: actions/checkout@v4

      - name: Build
        run: |
          make -j$(nproc)
          make cia

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: butterscotch-n3ds
          path: |
            *.3dsx
            *.cia
